name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Build React app
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-github-pages@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: dist
